/*******************************************************************************************|
|* Font Generated by:Burt's Font Parser ****(C) 2025 Burt O. Sumner all rights reserved**** |
|* Font Name: Chess_sprites                                                                |
|* Font Glyph Count: 7                                                                     |
|* Font Glyph Width: 20                                                                    |
|* Font Glyph Height: 16                                                                   |
|* Font Bitdepth: 1bpp                                                                     |
|* Font Generated w/ Palette: True                                                         |
|*******************************************************************************************/
#ifndef _CHESS_SPRITES_FONT_
#define _CHESS_SPRITES_FONT_

#ifdef __cplusplus
#include <cstdint>
extern "C" {
#else
#include <stdint.h>
#endif  /* C++ name mangler guard opener */

#define Chess_sprites_Glyph_Count 7U
#define Chess_sprites_Glyph_Width 20U
#define Chess_sprites_Glyph_Height 16U

/** Glyph cell row size in bytes */
#define Chess_sprites_Glyph_Cell_Row_Size 3U

/** Glyph cell size in bytes (Use this to index between glyphs) */
#define Chess_sprites_Glyph_Cell_Size 48U
#define Chess_sprites_Font_Bitdepth 1U


extern const uint32_t Chess_sprites_Glyph_Data[84];
#ifdef __cplusplus
}
#endif  /* C++ name mangler guard closer */
#endif  /* _CHESS_SPRITES_FONT_ */
