/* Header for zobrist table generated using /dev/random for rng */
#ifndef ZOBRIST_H
#define ZOBRIST_H

#ifdef __cplusplus
extern "C" {
#endif  /* C++ name mangler guard */

#include <stdint.h>
typedef enum e_zobrist_piece_id {
  WHITE_PAWN_ZID=0,
  WHITE_BISHOP_ZID,
  WHITE_ROOK_ZID,
  WHITE_KNIGHT_ZID,
  WHITE_QUEEN_ZID,
  WHITE_KING_ZID,
  BLACK_PAWN_ZID,
  BLACK_BISHOP_ZID,
  BLACK_ROOK_ZID,
  BLACK_KNIGHT_ZID,
  BLACK_QUEEN_ZID,
  BLACK_KING_ZID
} ZobristPieceID_t;

#define ZID_FROM_BOARD_PIECE_DATA(piece)\
  (EMPTY_IDX==piece\
      ? 0xFFFFFFFFUL\
      : (PIECE_IDX_MASK&piece)\
            + ((WHITE_FLAGBIT&piece) ? 0 : 6))

#define ZOBRIST_SIZE 809
#define ZOBRIST_PIECE_ID_COUNT 12
#define ZOBRIST_CASTLE_ID_COUNT 16
#define ZOBRIST_EN_PASSENT_ID_COUNT 8

#define ZOBRIST_CASTLE_ID_MASK (ZOBRIST_CASTLE_ID_COUNT-1)
#define ZOBRIST_EN_PASSENT_ID_MASK (ZOBRIST_EN_PASSENT_ID_COUNT-1)

#define BOARD_ZKEY_OFS 0
#define BOARD_ZKEY_COUNT (CHESS_BOARD_ROW_COUNT*CHESS_BOARD_FILE_COUNT*ZOBRIST_PIECE_ID_COUNT)
#define SIDE_TO_MOVE_ZKEY_OFS (BOARD_ZKEY_OFS + BOARD_ZKEY_COUNT)
#define SIDE_TO_MOVE_ZKEY_COUNT 1
#define CASTLE_ZKEY_OFS (SIDE_TO_MOVE_ZKEY_OFS + SIDE_TO_MOVE_ZKEY_COUNT)
#define CASTLE_ZKEY_COUNT ZOBRIST_CASTLE_ID_COUNT
#define EN_PASSENT_ZKEY_OFS (CASTLE_ZKEY_OFS + CASTLE_ZKEY_COUNT)
#define EN_PASSENT_ZKEY_COUNT ZOBRIST_EN_PASSENT_ID_COUNT
#define CASTLE_FORFEITURE_ZKEY_OFS (EN_PASSENT_ZKEY_OFS + EN_PASSENT_ZKEY_COUNT)
#define CASTLE_FORFEITURE_ZKEY_COUNT ZOBRIST_CASTLE_ID_COUNT

#define BOARD_ZKEY_ENTS(table)\
    (*(const u64(*)[CHESS_BOARD_ROW_COUNT][CHESS_BOARD_FILE_COUNT]\
       [ZOBRIST_PIECE_ID_COUNT]) (&table[BOARD_ZKEY_OFS]))
#define SIDE_TO_MOVE_ZKEY_ENT(table) (table[SIDE_TO_MOVE_ZKEY_OFS])
#define CASTLE_ZKEY_ENTS(table)\
  (*(const u64(*)[ZOBRIST_CASTLE_ID_COUNT])\
    (&table[CASTLE_ZKEY_OFS]))
#define EN_PASSENT_ZKEY_ENTS(table)\
  (*(const u64(*)[ZOBRIST_EN_PASSENT_ID_COUNT])\
    (&table[EN_PASSENT_ZKEY_OFS]))

#define CASTLE_FORFEITURE_ZKEY_ENTS(table)\
  (*(const u64(*)[ZOBRIST_CASTLE_ID_COUNT])\
    (&table[CASTLE_FORFEITURE_ZKEY_OFS]))
extern const unsigned long long int zobrist_table[ZOBRIST_SIZE];

#ifdef __cplusplus
}
#endif  /* C++ name mangler guard closer */

#endif /* ZOBRIST_H */
