#include "chess_board.h"

const ChessPiece_e BOARD_BACK_ROWS_INIT[16] = {
  ROOK_IDX, KNIGHT_IDX, BISHOP_IDX, QUEEN_IDX, KING_IDX, BISHOP_IDX, KNIGHT_IDX,
  ROOK_IDX, 
  PAWN_IDX, PAWN_IDX,   PAWN_IDX,   PAWN_IDX,  PAWN_IDX, PAWN_IDX,   PAWN_IDX, 
  PAWN_IDX,
};

const ChessPiece_e PROMOTION_SEL[4] = {
  QUEEN_IDX, ROOK_IDX, BISHOP_IDX, KNIGHT_IDX
};
